from .calendar import (
    calendar_tools,
    check_mac_calendar_conflicts,
    create_mac_calendar_event,
    delete_mac_calendar_event,
    find_mac_calendar_free_slots,
    list_mac_calendar_events,
    list_mac_calendars,
    show_mac_calendar_event,
    update_mac_calendar_event,
)
from .context import (
    context_tools,
    get_active_safari_url,
    get_clipboard_content,
    get_finder_selection_path,
    set_clipboard_content,
)
from .feedback import (
    feedback_tools,
    show_mac_notification,
    speak_mac_text,
)
from .finder import (
    compress_finder_selection,
    copy_finder_selection_to_folder,
    create_finder_folder,
    duplicate_finder_selection,
    finder_tools,
    list_finder_folder_contents,
    list_finder_selection_paths,
    open_path_in_finder,
    reveal_path_in_finder,
)
from .mail_contacts import (
    create_mail_draft,
    get_mac_contact_details,
    list_mail_message_summaries,
    mail_contact_tools,
    search_mac_contacts,
    send_mail_message,
)
from .media_files import (
    control_mac_music,
    empty_mac_trash,
    media_file_tools,
)
from .productivity import (
    create_mac_note,
    productivity_tools,
    send_imessage,
)
from .reminders import (
    complete_mac_reminder,
    create_mac_reminder,
    delete_mac_reminder,
    list_mac_reminder_lists,
    list_mac_reminders,
    reminder_tools,
    show_mac_reminder,
    update_mac_reminder,
)
from .system import (
    set_mac_dark_mode,
    set_mac_volume,
    system_tools,
    toggle_mac_mute,
)
from .system_state import (
    get_frontmost_app_info,
    get_mac_battery_status,
    get_mac_system_summary,
    get_mac_wifi_status,
    lock_mac_screen,
    open_system_settings_pane,
    start_mac_screensaver,
    system_state_tools,
)


all_mac_tools = [
    *system_tools,
    *system_state_tools,
    *feedback_tools,
    *productivity_tools,
    *reminder_tools,
    *calendar_tools,
    *mail_contact_tools,
    *finder_tools,
    *context_tools,
    *media_file_tools,
]


__all__ = [
    "all_mac_tools",
    "calendar_tools",
    "context_tools",
    "feedback_tools",
    "finder_tools",
    "mail_contact_tools",
    "media_file_tools",
    "productivity_tools",
    "reminder_tools",
    "system_tools",
    "system_state_tools",
    "check_mac_calendar_conflicts",
    "compress_finder_selection",
    "complete_mac_reminder",
    "control_mac_music",
    "create_mac_calendar_event",
    "create_finder_folder",
    "create_mail_draft",
    "create_mac_note",
    "create_mac_reminder",
    "copy_finder_selection_to_folder",
    "delete_mac_calendar_event",
    "delete_mac_reminder",
    "duplicate_finder_selection",
    "empty_mac_trash",
    "find_mac_calendar_free_slots",
    "get_active_safari_url",
    "get_clipboard_content",
    "get_frontmost_app_info",
    "get_finder_selection_path",
    "get_mac_battery_status",
    "get_mac_contact_details",
    "get_mac_system_summary",
    "get_mac_wifi_status",
    "list_finder_folder_contents",
    "list_finder_selection_paths",
    "list_mac_calendar_events",
    "list_mac_calendars",
    "list_mac_reminder_lists",
    "list_mac_reminders",
    "list_mail_message_summaries",
    "lock_mac_screen",
    "open_path_in_finder",
    "open_system_settings_pane",
    "reveal_path_in_finder",
    "search_mac_contacts",
    "send_imessage",
    "send_mail_message",
    "set_clipboard_content",
    "set_mac_dark_mode",
    "set_mac_volume",
    "show_mac_calendar_event",
    "show_mac_notification",
    "show_mac_reminder",
    "speak_mac_text",
    "start_mac_screensaver",
    "toggle_mac_mute",
    "update_mac_calendar_event",
    "update_mac_reminder",
]
